#!/usr/bin/env bash
set -euxo pipefail

# The reproducible run imports lamf_analysis (roicat_utils, code_ocean.capsule_data_utils,
# qc_info) and comb (behavior/ophys datasets + file_handling, pulled in by capsule_data_utils).
# Install both from source, editable, matching the sibling capsules.

cd /
git clone https://github.com/AllenNeuralDynamics/comb
cd /comb
git checkout for_gcamp_validation
pip install -e .

cd /
git clone https://github.com/AllenNeuralDynamics/lamf-analysis
cd /lamf-analysis
pip install -e .
